"""Bảng tin — FR-10.1 tới FR-10.6, ADR-015.

Chạy xuôi: tạo `feed_post` (bài và thiệp sinh nhật, ghim đứng đầu, ràng buộc
mỗi người mỗi ngày sinh nhật một thiệp), `feed_comment` và `feed_like` (mỗi
người mỗi bài một dòng, bỏ thích là đánh dấu xoá) kèm chỉ mục theo ghim và
ngày, theo tác giả, theo bài. Chạy ngược: bỏ ba bảng.
"""
# Generated by Django 5.2.6 on 2026-09-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Xoá lúc"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("bai_viet", "Bài viết"), ("sinh_nhat", "Sinh nhật")],
                        db_index=True,
                        default="bai_viet",
                        max_length=12,
                        verbose_name="Loại",
                    ),
                ),
                ("body", models.TextField(verbose_name="Nội dung")),
                (
                    "birthday_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày sinh nhật"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Ghim"
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ghim lúc"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tác giả",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xoá",
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người ghim",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birthday_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người được chúc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài",
                "verbose_name_plural": "Bài",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Xoá lúc"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xoá",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thích",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="feed.post",
                        verbose_name="Bài",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt thích",
                "verbose_name_plural": "Lượt thích",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Xoá lúc"
                    ),
                ),
                ("body", models.CharField(max_length=500, verbose_name="Nội dung")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người viết",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xoá",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feed.post",
                        verbose_name="Bài",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Bình luận",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-is_pinned", "-created_at"], name="post_pinned_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="post_author_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "sinh_nhat")),
                fields=("subject", "birthday_on"),
                name="post_birthday_unique_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="like_unique_post_user"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="comment_post_created_idx"
            ),
        ),
    ]
