"""Tài nguyên dùng chung chia theo mục — FR-13.1 tới FR-13.4, ADR-017.

Chạy xuôi: tạo `resources_resourcecategory` (tên duy nhất khi chưa xoá) và
`resources_resource` kèm chỉ mục (mục, trạng thái), người giữ, và GIN pg_trgm
trên tên để tìm theo tên. Chạy ngược: bỏ hai bảng.
"""
# Generated by Django 5.2.6 on 2026-09-07 02:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_pg_trgm"),
        ("org", "0003_userprofile_birthday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Xoá lúc"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Tên mục")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Thứ tự"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xoá",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mục tài nguyên",
                "verbose_name_plural": "Mục tài nguyên",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Xoá lúc"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Liên kết"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trong", "Trống"),
                            ("dang_dung", "Đang dùng"),
                            ("khoa", "Khoá"),
                            ("hong", "Hỏng"),
                        ],
                        db_index=True,
                        default="trong",
                        max_length=12,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xoá",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="org.department",
                        verbose_name="Bộ phận dùng",
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources_held",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người giữ",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.resourcecategory",
                        verbose_name="Mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài nguyên",
                "verbose_name_plural": "Tài nguyên",
                "ordering": ["category__order", "category__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcecategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="resource_category_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category", "status"], name="resource_cat_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="resource_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
