"""Tên mục tài nguyên không phân biệt hoa thường — rà soát 07.09.2026.

Chạy xuôi: thay ràng buộc `resource_category_name_unique` (tên) bằng
lower(tên), vẫn chỉ tính mục chưa xoá. Chạy ngược: đặt lại ràng buộc cũ.
"""
# Generated by Django 5.2.6 on 2026-09-07 08:47

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_tai_nguyen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resourcecategory",
            name="resource_category_name_unique",
        ),
        migrations.AddConstraint(
            model_name="resourcecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="resource_category_name_unique",
            ),
        ),
    ]
