# Generated by Django 5.2.6 on 2026-08-29 04:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_userprofile_profile_full_name_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('name', models.CharField(max_length=120, verbose_name='Tên bảng')),
                ('code', models.SlugField(help_text='Tên kỹ thuật, tiếng Anh, dùng làm khoá trong cơ sở dữ liệu.', max_length=60, unique=True, verbose_name='Tên kỹ thuật')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='org.department', verbose_name='Bộ phận sở hữu')),
            ],
            options={
                'verbose_name': 'Bảng dữ liệu',
                'verbose_name_plural': 'Bảng dữ liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu')),
                ('val_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày')),
                ('val_customer', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Khách hàng')),
                ('val_phone', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Số điện thoại')),
                ('val_revenue', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='Doanh thu')),
                ('val_seller', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Người bán')),
                ('val_product', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Sản phẩm')),
                ('val_status', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Trạng thái')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.department', verbose_name='Bộ phận')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.team', verbose_name='Team')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='forms_builder.tabledef', verbose_name='Bảng')),
            ],
            options={
                'verbose_name': 'Bản ghi',
                'verbose_name_plural': 'Bản ghi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table', '-created_at'], name='record_table_time_idx'), models.Index(fields=['table', 'val_date'], name='record_table_date_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='record_data_gin')],
            },
        ),
        migrations.CreateModel(
            name='ColumnDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('name', models.CharField(max_length=120, verbose_name='Nhãn hiển thị')),
                ('code', models.SlugField(help_text='Tên kỹ thuật, tiếng Anh, dùng làm khoá trong cơ sở dữ liệu.', max_length=60, verbose_name='Tên kỹ thuật')),
                ('field_type', models.CharField(choices=[('text', 'Chữ ngắn'), ('long_text', 'Chữ dài'), ('integer', 'Số nguyên'), ('decimal', 'Số thập phân'), ('money', 'Tiền'), ('date', 'Ngày'), ('datetime', 'Ngày giờ'), ('boolean', 'Đúng sai'), ('choice', 'Chọn một')], default='text', max_length=20, verbose_name='Kiểu dữ liệu')),
                ('meaning', models.CharField(blank=True, choices=[('date', 'Ngày'), ('customer', 'Khách hàng'), ('phone', 'Số điện thoại'), ('revenue', 'Doanh thu'), ('seller', 'Người bán'), ('product', 'Sản phẩm'), ('status', 'Trạng thái')], db_index=True, help_text='Cột có nhãn được tách ra cột riêng có chỉ mục, và vào được báo cáo tổng hợp.', max_length=20, verbose_name='Nhãn ý nghĩa')),
                ('required', models.BooleanField(default=False, verbose_name='Bắt buộc nhập')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_computed', models.BooleanField(default=False, verbose_name='Là cột tính sẵn')),
                ('compute_op', models.CharField(blank=True, choices=[('add', 'Cộng — A + B'), ('subtract', 'Trừ — A − B'), ('multiply', 'Nhân — A × B'), ('divide', 'Chia — A ÷ B'), ('percent', 'Phần trăm — A ÷ B × 100')], max_length=12, verbose_name='Phép tính')),
                ('compute_left', models.SlugField(blank=True, max_length=60, verbose_name='Toán hạng A')),
                ('compute_right', models.SlugField(blank=True, max_length=60, verbose_name='Toán hạng B')),
                ('compute_decimals', models.PositiveSmallIntegerField(default=2, verbose_name='Số chữ số thập phân')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='forms_builder.tabledef', verbose_name='Bảng')),
            ],
            options={
                'verbose_name': 'Cột',
                'verbose_name_plural': 'Cột',
                'ordering': ['table', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('table', 'code'), name='column_code_unique_per_table')],
            },
        ),
    ]
