# Generated by Django 5.2.6 on 2026-08-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='columndef',
            constraint=models.UniqueConstraint(condition=models.Q(('meaning', ''), _negated=True), fields=('table', 'meaning'), name='column_meaning_unique_per_table'),
        ),
    ]
