# Generated by Django 5.2.6 on 2026-08-29 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0002_columndef_column_meaning_unique_per_table'),
        ('org', '0002_userprofile_profile_full_name_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('name', models.CharField(max_length=120, verbose_name='Nhãn hiển thị')),
                ('code', models.SlugField(help_text='Tên kỹ thuật, tiếng Anh, dùng làm khoá trong cơ sở dữ liệu.', max_length=60, verbose_name='Tên kỹ thuật')),
                ('field_type', models.CharField(choices=[('text', 'Chữ ngắn'), ('long_text', 'Chữ dài'), ('integer', 'Số nguyên'), ('decimal', 'Số thập phân'), ('money', 'Tiền'), ('date', 'Ngày'), ('datetime', 'Ngày giờ'), ('boolean', 'Đúng sai'), ('choice', 'Chọn một')], default='text', max_length=20, verbose_name='Kiểu dữ liệu')),
                ('meaning', models.CharField(blank=True, choices=[('date', 'Ngày'), ('customer', 'Khách hàng'), ('phone', 'Số điện thoại'), ('revenue', 'Doanh thu'), ('seller', 'Người bán'), ('product', 'Sản phẩm'), ('status', 'Trạng thái')], db_index=True, max_length=20, verbose_name='Nhãn ý nghĩa')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='Câu gợi ý dưới ô nhập')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_defs', to='org.department', verbose_name='Bộ phận')),
            ],
            options={
                'verbose_name': 'Định nghĩa trường',
                'verbose_name_plural': 'Định nghĩa trường',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('name', models.CharField(max_length=120, verbose_name='Tên biểu mẫu')),
                ('code', models.SlugField(help_text='Tên kỹ thuật, tiếng Anh, dùng làm khoá trong cơ sở dữ liệu.', max_length=60, unique=True, verbose_name='Tên kỹ thuật')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='org.department', verbose_name='Bộ phận áp dụng')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='forms_builder.tabledef', verbose_name='Bảng đích')),
            ],
            options={
                'verbose_name': 'Biểu mẫu',
                'verbose_name_plural': 'Biểu mẫu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('required', models.BooleanField(default=False, verbose_name='Bắt buộc nhập')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='forms_builder.fielddef', verbose_name='Định nghĩa trường')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.formdef', verbose_name='Biểu mẫu')),
            ],
            options={
                'verbose_name': 'Trường trong biểu mẫu',
                'verbose_name_plural': 'Trường trong biểu mẫu',
                'ordering': ['form', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormTableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='forms_builder.columndef', verbose_name='Cột đích')),
                ('form_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='forms_builder.formfield', verbose_name='Trường biểu mẫu')),
            ],
            options={
                'verbose_name': 'Liên kết trường và cột',
                'verbose_name_plural': 'Liên kết trường và cột',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('action', models.CharField(choices=[('view', 'Xem bảng'), ('fill', 'Điền biểu mẫu'), ('edit', 'Sửa dữ liệu')], db_index=True, max_length=10, verbose_name='Được làm gì')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='forms_builder.formdef', verbose_name='Biểu mẫu')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cấp')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='forms_builder.tabledef', verbose_name='Bảng dữ liệu')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='org.team', verbose_name='Cấp cho team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL, verbose_name='Cấp cho người')),
            ],
            options={
                'verbose_name': 'Quyền cấp thêm',
                'verbose_name_plural': 'Quyền cấp thêm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fielddef',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='field_code_unique_per_department'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'field'), name='form_field_unique_per_form'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['user', 'action'], name='grant_user_action_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['team', 'action'], name='grant_team_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('form__isnull', True), ('table__isnull', False)), models.Q(('form__isnull', False), ('table__isnull', True)), _connector='OR'), name='grant_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='grant_exactly_one_holder'),
        ),
    ]
