# Generated by Django 5.2.6 on 2026-08-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_fielddef_formdef_formfield_formtablelink_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledef',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False, help_text='Mọi người trong bộ phận sở hữu thấy mọi dòng, không phân biệt cấp bậc. Dùng cho bảng là hàng đợi việc chung như bảng vận đơn. Bảng báo cáo thì để tắt, giữ phạm vi theo cấp bậc.', verbose_name='Bảng dùng chung'),
        ),
    ]
