# Generated by Django 5.2.6 on 2026-08-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0004_tabledef_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddef',
            name='default_value',
            field=models.CharField(blank=True, help_text='Điền sẵn vào ô khi mở biểu mẫu. Để trống nếu không có.', max_length=200, verbose_name='Giá trị mặc định'),
        ),
    ]
