# Generated by Django 5.2.6 on 2026-09-10 10:03

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('forms_builder', '0009_record_updated_phone_idx'),
        ('org', '0003_userprofile_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='datarecord',
            index=models.Index(fields=['table', 'created_at', 'id'], include=('deleted_at', 'updated_at', 'created_by'), name='record_master_cover_idx'),
        ),
    ]
