# Generated by Django 5.2.6 on 2026-09-15 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0011_delivery_view_mode'),
        ('org', '0004_accounting_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledef',
            name='receives_orders',
            field=models.BooleanField(default=False, editable=False, verbose_name='Nhận đơn mới'),
        ),
        migrations.AddField(
            model_name='tabledef',
            name='workflow',
            field=models.CharField(blank=True, default='', editable=False, max_length=24, verbose_name='Nghiệp vụ bảng'),
        ),
        migrations.AddConstraint(
            model_name='tabledef',
            constraint=models.UniqueConstraint(condition=models.Q(('receives_orders', True)), fields=('receives_orders',), name='one_order_destination'),
        ),
    ]
