# Generated by Django 5.2.6 on 2026-09-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0014_remove_tabledef_receives_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="columndef",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Cột vẫn giữ nguyên dữ liệu nhưng không hiện ở đâu. Quản lý bảng bật tắt trong hộp Cột.",
                verbose_name="Ẩn với mọi người",
            ),
        ),
    ]
