# Generated by Django 5.2.6 on 2026-08-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('actor_label', models.CharField(blank=True, max_length=150, verbose_name='Tên người thực hiện')),
                ('action', models.CharField(choices=[('login', 'Đăng nhập'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('create', 'Tạo'), ('update', 'Sửa'), ('delete', 'Xoá'), ('export', 'Xuất dữ liệu'), ('import', 'Nhập dữ liệu'), ('permission', 'Đổi quyền'), ('denied', 'Từ chối truy cập')], db_index=True, max_length=20, verbose_name='Hành động')),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Loại đối tượng')),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Mã đối tượng')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='Chi tiết')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_action_time_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
