# Generated by Django 5.2.6 on 2026-08-28 10:07

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['actor_label'], name='audit_actor_label_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
