# Generated by Django 5.2.6 on 2026-09-03 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auditlog_audit_actor_label_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Tạo lúc"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Sửa lúc"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("import", "Nhập tệp"),
                            ("export", "Xuất tệp"),
                            ("backup", "Sao lưu"),
                            ("cleanup", "Dọn dẹp"),
                        ],
                        db_index=True,
                        max_length=12,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Chờ xác nhận"),
                            ("pending", "Chờ xử lý"),
                            ("running", "Đang chạy"),
                            ("done", "Xong"),
                            ("failed", "Thất bại"),
                            ("stale", "Kẹt — worker không chạy"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Mô tả"),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        verbose_name="Loại đối tượng",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        verbose_name="Mã đối tượng",
                    ),
                ),
                (
                    "input_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Tệp đầu vào"
                    ),
                ),
                (
                    "result_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Tệp kết quả"
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="Đã xử lý"),
                ),
                (
                    "total",
                    models.PositiveIntegerField(default=0, verbose_name="Tổng số"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Tóm tắt"),
                ),
                ("error", models.TextField(blank=True, verbose_name="Lỗi")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bắt đầu lúc"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kết thúc lúc"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tác vụ nền",
                "verbose_name_plural": "Tác vụ nền",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="job_status_time_idx"
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"], name="job_owner_time_idx"
                    ),
                ],
            },
        ),
    ]
