# Generated by Django 5.2.6 on 2026-10-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_backgroundjob_kind_recompute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField(verbose_name="Mã lần nộp")),
                ("kind", models.CharField(max_length=30, verbose_name="Loại")),
                (
                    "object_id",
                    models.BigIntegerField(null=True, verbose_name="Đối tượng đã ghi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submission_receipt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "key"), name="core_submission_actor_key"
                    )
                ],
            },
        ),
    ]
