# Generated by Django 5.2.6 on 2026-08-29 07:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0003_fielddef_formdef_formfield_formtablelink_grant_and_more'),
        ('org', '0002_userprofile_profile_full_name_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('phone', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Số điện thoại')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách')),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False, verbose_name='Trong danh sách đen')),
                ('blacklist_reason', models.CharField(blank=True, max_length=300, verbose_name='Lý do')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Mã sản phẩm')),
                ('unit', models.CharField(default='cái', max_length=40, verbose_name='Đơn vị tính')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang bán')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên nhóm')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Nhóm sản phẩm',
                'verbose_name_plural': 'Nhóm sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Mã đơn')),
                ('market', models.CharField(choices=[('us', 'Hoa Kỳ'), ('ca', 'Canada'), ('ph', 'Philippines')], db_index=True, default='us', max_length=4, verbose_name='Quốc gia')),
                ('state', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Bang')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Thành phố')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='Mã bưu chính')),
                ('address_line', models.CharField(blank=True, max_length=300, verbose_name='Số nhà, đường')),
                ('payment_method', models.CharField(choices=[('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('cod', 'Thu hộ khi giao'), ('wallet', 'Ví điện tử')], default='card', max_length=12, verbose_name='Phương thức thanh toán')),
                ('currency', models.CharField(choices=[('VND', 'Việt Nam đồng'), ('USD', 'Đô la Mỹ')], default='USD', max_length=3, verbose_name='Loại tiền tệ')),
                ('sub_unit', models.CharField(blank=True, max_length=120, verbose_name='Đơn vị phụ')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Tổng tiền')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='Khách hàng')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='org.department', verbose_name='Bộ phận')),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='forms_builder.datarecord', verbose_name='Dòng trên bảng vận đơn')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_sold', to=settings.AUTH_USER_MODEL, verbose_name='Người bán')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='org.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Đơn giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='orders.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Dòng sản phẩm',
                'verbose_name_plural': 'Dòng sản phẩm',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='orders.productgroup', verbose_name='Nhóm'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['department', '-created_at'], name='order_dept_time_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', '-created_at'], name='order_owner_time_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', '-created_at'], name='order_market_time_idx'),
        ),
    ]
