# Generated by Django 5.2.6 on 2026-09-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0009_record_updated_phone_idx'),
        ('orders', '0003_waybillitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_assignments', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('marketing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_assignments', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='forms_builder.datarecord')),
            ],
        ),
    ]
