# Generated by Django 5.2.6 on 2026-09-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_assignment_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='waybillitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Đơn vị tính'),
        ),
    ]
