# Generated by Django 5.2.6 on 2026-09-12 05:34

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0010_master_cover_index'),
        ('orders', '0006_line_unit_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('reference', models.CharField(max_length=200)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('operation', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_documents', to='forms_builder.datarecord')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('file_path', models.CharField(max_length=300)),
                ('file_name', models.CharField(max_length=200)),
                ('file_kind', models.CharField(max_length=8)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='orders.paymentdocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['record', 'created_at', 'id'], name='payment_record_created'),
        ),
        migrations.AddConstraint(
            model_name='paymentdocument',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('reference'), models.F('record'), condition=models.Q(('deleted_at__isnull', True)), name='payment_ref_per_record'),
        ),
        migrations.AddConstraint(
            model_name='paymentdocument',
            constraint=models.UniqueConstraint(fields=('created_by', 'operation'), name='payment_create_operation'),
        ),
    ]
