# Generated by Django 5.2.6 on 2026-09-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentdocument_paymentimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('cod', 'Thu hộ khi giao'), ('wallet', 'Ví điện tử'), ('zelle', 'Zelle'), ('paypal', 'PayPal')], default='zelle', max_length=12, verbose_name='Phương thức thanh toán'),
        ),
    ]
