# Generated by Django 5.2.6 on 2026-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_more_markets_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Thẻ"),
                    ("transfer", "Chuyển khoản"),
                    ("cod", "Thu hộ khi giao"),
                    ("wallet", "Ví điện tử"),
                    ("zelle", "Zelle"),
                    ("paypal", "PayPal"),
                    ("visa_web", "Visa/Website"),
                    ("cheque", "Cheque"),
                    ("western", "Western Union"),
                    ("ria", "RIA"),
                    ("moneygram", "Money Gram"),
                ],
                default="zelle",
                max_length=12,
                verbose_name="Phương thức thanh toán",
            ),
        ),
    ]
