# Generated by Django 5.2.6 on 2026-08-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên bộ phận')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Mã')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
            ],
            options={
                'verbose_name': 'Bộ phận',
                'verbose_name_plural': 'Bộ phận',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('name', models.CharField(max_length=100, verbose_name='Tên team')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='org.department', verbose_name='Bộ phận')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng nhóm')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Họ tên')),
                ('rank', models.CharField(choices=[('staff', 'Nhân viên'), ('leader', 'Trưởng nhóm'), ('manager', 'Quản lý'), ('admin', 'Quản trị viên')], db_index=True, default='staff', max_length=10, verbose_name='Cấp bậc')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Buộc đổi mật khẩu')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần sai liên tiếp')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Khoá tới')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Đăng nhập lần cuối')),
                ('session_epoch', models.PositiveIntegerField(default=0, verbose_name='Mốc phiên')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='org.department', verbose_name='Bộ phận')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.team', verbose_name='Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân sự',
                'verbose_name_plural': 'Hồ sơ nhân sự',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='team_unique_trong_bo_phan'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department', 'rank'], name='profile_dept_rank_idx'),
        ),
    ]
