# Generated by Django 5.2.6 on 2026-08-28 10:07

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Chỉ mục GIN dùng gin_trgm_ops, nên phần mở rộng pg_trgm phải bật trước
        ('core', '0002_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='profile_full_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
