# Generated by Django 5.2.6 on 2026-09-25 03:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_userprofile_staff_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'base_manager_name': 'all_objects', 'ordering': ['full_name'], 'verbose_name': 'Hồ sơ nhân sự', 'verbose_name_plural': 'Hồ sơ nhân sự'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('staff', 'Nhân viên'), ('leader', 'Trưởng nhóm'), ('manager', 'Quản lý'), ('ceo', 'Giám đốc'), ('admin', 'Quản trị viên')], db_index=True, default='staff', max_length=10, verbose_name='Cấp bậc'),
        ),
    ]
