"""Tên mục tài liệu không phân biệt hoa thường — rà soát 07.09.2026.

Chạy xuôi: thay ràng buộc `doc_category_name_unique` (bộ phận, tên) bằng
(bộ phận, lower(tên)), vẫn chỉ tính mục chưa xoá và coi hai mục "toàn công
ty" là cùng bộ phận. Chạy ngược: đặt lại ràng buộc cũ.
"""
# Generated by Django 5.2.6 on 2026-09-07 08:47

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_tai_lieu_va_muc"),
        ("org", "0003_userprofile_birthday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentcategory",
            name="doc_category_name_unique",
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("department"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="doc_category_name_unique",
                nulls_distinct=False,
            ),
        ),
    ]
