# Generated by Django 5.2.6 on 2026-08-29 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0003_fielddef_formdef_formfield_formtablelink_grant_and_more'),
        ('org', '0002_userprofile_profile_full_name_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sửa lúc')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xoá lúc')),
                ('report_date', models.DateField(db_index=True, verbose_name='Báo cáo cho ngày')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Lưu theo giờ quốc tế, hiển thị theo giờ Việt Nam — BR-7.', verbose_name='Thời điểm nộp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xoá')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='org.department', verbose_name='Bộ phận')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='forms_builder.formdef', verbose_name='Biểu mẫu')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report', to='forms_builder.datarecord', verbose_name='Dòng dữ liệu')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='org.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Báo cáo hằng ngày',
                'verbose_name_plural': 'Báo cáo hằng ngày',
                'ordering': ['-report_date', '-submitted_at'],
                'indexes': [models.Index(fields=['department', '-report_date'], name='report_dept_date_idx'), models.Index(fields=['created_by', '-report_date'], name='report_owner_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('form', 'created_by', 'report_date'), name='report_unique_per_person_per_day')],
            },
        ),
    ]
