# Generated by Django 5.2.6 on 2026-09-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0009_record_updated_phone_idx'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Sale'), ('mkt', 'Marketing'), ('delivery', 'Vận đơn')], max_length=12)),
                ('columns', models.JSONField(default=dict)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_report', to='forms_builder.tabledef')),
            ],
            options={
                'verbose_name': 'Nguồn báo cáo ERP',
            },
        ),
    ]
