# Generated by Django 5.2.6 on 2026-09-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('forms_builder', '0009_record_updated_phone_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=100)),
                ('property', models.CharField(default='value', max_length=12)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.gridmutationreceipt')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_builder.datarecord')),
            ],
            options={
                'indexes': [models.Index(fields=['record', '-id'], name='crm_history_record_id')],
            },
        ),
    ]
